[package]
name = "cube_game"
version = "0.1.0"
authors = ["Kranando <41551796+Kranando@users.noreply.github.com>"]

[dependencies]
piston_window = "0.81.0"
ncollide = "0.14.1"
find_folder = "*"
gfx_device_gl = "0.15.3"
gfx = "0.17.1"
piston2d-gfx_graphics = "0.52.0"
